"""Correct data

Revision ID: 34b106153d55
Revises: 594aba519fb9
Create Date: 2024-02-19 17:00:00.574287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b106153d55'
down_revision: Union[str, None] = '594aba519fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('rooms', 'desctiption')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('desctiption', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###
